
all:
    debug: False
labweb:
    production: false # this should be false during development. It will create proxy server for fronted server to the backend server
    log_directory: "logs" 
    static_files_directory: "labweb/frontend/dist"
motion_tracker:
    camera: # settings for camera control
        width: 640
        height: 360
        fps: 60
        device_index: 0
    inactive_timer: 300 # turn camera off and reset motion tracker if no one is looking at camera (get_frames) for x seconds
    calibration_stickers:
        min_area: 75
        coordinates_local:
            tl: 
                x: 0
                y: 40
            tm: 
                x: 45
                y: 40
            tr:
                x: 90
                y: 40
            bl:
                x: 0
                y: 20
            bm:
                x: 45
                y: 20
            br:
                x: 90
                y: 20
    tracking:
        frame_timeout: 1 # tracking should shutdown if no frames are received after x seconds
        roi:
            width: 100 # region of interest width
            height: 100 # region of interest height
        std_multiplier: [1, 5, 5]
    recording:
        default_experiment_name: "default"
        save_directory: "./data"
                
    

