site_name: "motiontrackerlab"
site_description: "Automatic Realtime Motion Tracking and Recording"
site_url: "https://PiPhysics.github.io/MotionTrackerLab"
repo_url: "https://github.com/PiPhysics/MotionTrackerLab"
edit_uri: "blob/master/docs/"
repo_name: "PiPhysics/MotionTrackerLab"
watch: [README.md, CONTRIBUTING.md, labconfig/, motiontracker/, labweb/]

nav:
- Home:
  - Overview: index.md
  - License: license.md
- Tutorials:
  - Hardware Setup: tutorials/materials-hardware.md
  - Software Setup: tutorials/software-setup.md
  - Tracking Tutorial: tutorials/software-beginner.md
- How To Guides:
  - Advanced Tracking: how-to-guides/software-advanced.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Project Overview: development/project-overview.md
  - Contributing: contributing.md

theme:
  name: material
  features:
  - content.code.annotate
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/style.css
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- callouts
- pymdownx.details
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.txt
- section-index
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          show_submodules: no

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/JeremyBYU